name: 🚀 Deploy Site
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    name: Eleventy Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Install Node modules
        run: npm install
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.1
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site 
          github_token: ${{ secrets.GITHUB_TOKEN }}
